services:
  dockermanger:
    build:
      context: .
      dockerfile: Dockerfile

    image: dockermanger:dev
    container_name: dockermanger
    hostname: dockermanger
    restart: unless-stopped

    ports:
      - "${WEB_PORT:-5001}:80"
      - "${SSH_PORT:-2222}:22"

    environment:
      TZ: ${TZ:-America/Chicago}
      STACKS_DIR: ${STACKS_DIR:-/opt/stacks}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STACKS_DIR:-/opt/stacks}:${STACKS_DIR:-/opt/stacks}
      - ./data:/data
