#!/usr/bin/env bash
set -Eeuo pipefail
umask 022

# DockerManger native Debian/Proxmox installer.
# Additive to the repository: copies app/runtime files to host paths and never
# edits repository files. Safe to re-run after git pull or to repair a host.

# git clone https://github.com/bmartino1/DockerManger.git
# cd DockerManger
# chmod +x host_installer.sh
# ./host_installer.sh

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
APP_SRC="$SCRIPT_DIR/app"
TERMINAL_SRC="$SCRIPT_DIR/container/terminal"
PHP_INI_SRC="$SCRIPT_DIR/container/php/docker-manager.ini"
REPO_DATA_SRC="$SCRIPT_DIR/data"

APP_DST="/var/www/dockermanger"
TERMINAL_DST="/opt/dockermanger-terminal"
CONFIG_DIR="/etc/dockermanger"
INSTALLER_CONF="$CONFIG_DIR/installer.conf"
ENV_DST="$CONFIG_DIR/dockermanger.env"
DATA_DIR="/data"
DEFAULT_STACKS_DIR="/opt/stacks"
ACME_DIR="/var/www/acme-challenge"
NGINX_DST="/etc/nginx/sites-available/dockermanger.conf"
SYSTEMD_DST="/etc/systemd/system/dockermanger-terminal.service"
TMP_DIR="$(mktemp -d /tmp/dockermanger-host-installer.XXXXXX)"

log(){ printf '\n\033[1;34m[DockerManger]\033[0m %s\n' "$*"; }
warn(){ printf '\n\033[1;33m[WARNING]\033[0m %s\n' "$*" >&2; }
die(){ printf '\n\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
cleanup(){ rm -rf -- "$TMP_DIR"; }
trap cleanup EXIT
trap 'printf "\n[ERROR] Installer failed at line %s: %s\n" "$LINENO" "$BASH_COMMAND" >&2' ERR

[[ ${EUID:-$(id -u)} -eq 0 ]] || die "Run as root."
[[ -f /etc/os-release ]] || die "Cannot identify OS."
# shellcheck disable=SC1091
. /etc/os-release
[[ "${ID:-}" == "debian" || " ${ID_LIKE:-} " == *" debian "* ]] || die "Debian/Proxmox host required."
[[ -f "$APP_SRC/public/index.php" ]] || die "Run host_installer.sh from the DockerManger repository root."
[[ -f "$TERMINAL_SRC/server.js" && -f "$TERMINAL_SRC/package.json" ]] || die "Missing container/terminal source files."
[[ -f "$PHP_INI_SRC" ]] || die "Missing container/php/docker-manager.ini."

# Defaults. Existing saved choices override these. Environment variables supplied
# to this invocation override both, making unattended changes easy.
DEF_HTTP_PORT=80
DEF_HTTPS_PORT=443
DEF_STACKS_DIR="$DEFAULT_STACKS_DIR"
DEF_TIMEZONE="America/Chicago"
DEF_INSTALL_DOCKER=true
DEF_INSTALL_SSHD=true
DEF_ENABLE_CONSOLE=false
DEF_MANAGE_STACK_PERMS=true

if [[ -f "$INSTALLER_CONF" ]]; then
  # This file is generated by us as shell-safe %q assignments.
  # shellcheck disable=SC1090
  source "$INSTALLER_CONF"
fi

HTTP_PORT="${HTTP_PORT:-${SAVED_HTTP_PORT:-$DEF_HTTP_PORT}}"
HTTPS_PORT="${HTTPS_PORT:-${SAVED_HTTPS_PORT:-$DEF_HTTPS_PORT}}"
STACKS_DIR="${STACKS_DIR:-${SAVED_STACKS_DIR:-$DEF_STACKS_DIR}}"
TIMEZONE="${TIMEZONE:-${SAVED_TIMEZONE:-$DEF_TIMEZONE}}"
INSTALL_DOCKER="${INSTALL_DOCKER:-${SAVED_INSTALL_DOCKER:-$DEF_INSTALL_DOCKER}}"
INSTALL_SSHD="${INSTALL_SSHD:-${SAVED_INSTALL_SSHD:-$DEF_INSTALL_SSHD}}"
ENABLE_CONSOLE="${ENABLE_CONSOLE:-${SAVED_ENABLE_CONSOLE:-$DEF_ENABLE_CONSOLE}}"
MANAGE_STACK_PERMS="${MANAGE_STACK_PERMS:-${SAVED_MANAGE_STACK_PERMS:-$DEF_MANAGE_STACK_PERMS}}"

valid_port(){ [[ "$1" =~ ^[0-9]+$ ]] && ((10#$1 >= 1 && 10#$1 <= 65535)); }
valid_bool(){ [[ "$1" == true || "$1" == false ]]; }
valid_port "$HTTP_PORT" || die "Invalid HTTP_PORT=$HTTP_PORT"
valid_port "$HTTPS_PORT" || die "Invalid HTTPS_PORT=$HTTPS_PORT"
[[ "$HTTP_PORT" != "$HTTPS_PORT" ]] || die "HTTP_PORT and HTTPS_PORT must differ."
[[ "$STACKS_DIR" == /* ]] || die "STACKS_DIR must be absolute."
valid_bool "$INSTALL_DOCKER" || die "INSTALL_DOCKER must be true/false."
valid_bool "$INSTALL_SSHD" || die "INSTALL_SSHD must be true/false."
valid_bool "$ENABLE_CONSOLE" || die "ENABLE_CONSOLE must be true/false."
valid_bool "$MANAGE_STACK_PERMS" || die "MANAGE_STACK_PERMS must be true/false."

install -d -m 0755 "$CONFIG_DIR"
{
  printf 'SAVED_HTTP_PORT=%q\n' "$HTTP_PORT"
  printf 'SAVED_HTTPS_PORT=%q\n' "$HTTPS_PORT"
  printf 'SAVED_STACKS_DIR=%q\n' "$STACKS_DIR"
  printf 'SAVED_TIMEZONE=%q\n' "$TIMEZONE"
  printf 'SAVED_INSTALL_DOCKER=%q\n' "$INSTALL_DOCKER"
  printf 'SAVED_INSTALL_SSHD=%q\n' "$INSTALL_SSHD"
  printf 'SAVED_ENABLE_CONSOLE=%q\n' "$ENABLE_CONSOLE"
  printf 'SAVED_MANAGE_STACK_PERMS=%q\n' "$MANAGE_STACK_PERMS"
} > "$TMP_DIR/installer.conf"
install -m 0644 "$TMP_DIR/installer.conf" "$INSTALLER_CONF"

cat <<EOF
DockerManger native host install/repair
  OS:          ${PRETTY_NAME:-${ID:-unknown}}
  HTTP/HTTPS:  $HTTP_PORT / $HTTPS_PORT
  Stacks:      $STACKS_DIR
  Persistent:  $DATA_DIR (preserved)
  Settings:    $INSTALLER_CONF
  Console:     $ENABLE_CONSOLE
EOF
[[ "$ENABLE_CONSOLE" == true ]] && warn "Native browser console is enabled; its local target is a shell on this host."

log "Installing host packages and side utilities"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends \
  nginx php-fpm php-cli openssh-client openssl nodejs npm build-essential python3 \
  acl bash curl wget ca-certificates git jq nano mc less vim-tiny procps psmisc \
  iproute2 iputils-ping net-tools dnsutils traceroute netcat-openbsd socat \
  lsof rsync locales tzdata gnupg unzip zip tree file htop

# Explicitly verify the requested side utilities.
for cmd in mc ping nc nslookup dig traceroute curl wget jq rsync lsof ss ip; do
  command -v "$cmd" >/dev/null || die "Required utility '$cmd' is still missing after package installation."
done

if grep -Eq '^# *en_US.UTF-8 UTF-8' /etc/locale.gen; then
  sed -i 's/^# *\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
fi
locale-gen en_US.UTF-8 >/dev/null
update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

if [[ "$INSTALL_SSHD" == true ]]; then
  log "Installing/enabling OpenSSH server"
  apt-get install -y --no-install-recommends openssh-server
  systemctl enable --now ssh
fi

if [[ "$INSTALL_DOCKER" == true ]]; then
  log "Installing/repairing Docker Engine + Compose v2"
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o "$TMP_DIR/docker.asc"
  install -m 0644 "$TMP_DIR/docker.asc" /etc/apt/keyrings/docker.asc
  DOCKER_CODENAME="${VERSION_CODENAME:-}"
  [[ -n "$DOCKER_CODENAME" ]] || die "VERSION_CODENAME missing from /etc/os-release."
  printf 'deb [arch=%s signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian %s stable\n' \
    "$(dpkg --print-architecture)" "$DOCKER_CODENAME" > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi

PHP_VERSION="$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;' 2>/dev/null)"
PHP_FPM_SERVICE="php${PHP_VERSION}-fpm"
PHP_FPM_SOCK="/run/php/php${PHP_VERSION}-fpm.sock"
PHP_FPM_POOL="/etc/php/${PHP_VERSION}/fpm/pool.d/www.conf"
PHP_FPM_OVERRIDE="/etc/php/${PHP_VERSION}/fpm/pool.d/zz-dockermanger.conf"
PHP_FPM_DROPIN="/etc/systemd/system/${PHP_FPM_SERVICE}.service.d"
[[ -f "$PHP_FPM_POOL" ]] || die "PHP-FPM pool missing: $PHP_FPM_POOL"

log "Refreshing application copy; preserving runtime/stack data"
install -d -m 0755 "$APP_DST" "$TERMINAL_DST" "$DATA_DIR/certs" "$DATA_DIR/ssh" "$DATA_DIR/compose_stacks" "$STACKS_DIR" "$ACME_DIR/.well-known/acme-challenge"
# /var/www/dockermanger is a deployed copy and is refreshed from Git on rerun.
rsync -a --delete --exclude='.git' "$APP_SRC/" "$APP_DST/"
chown -R www-data:www-data "$APP_DST"
# Never delete or overwrite existing runtime data. Only seed files that are absent.
if [[ -d "$REPO_DATA_SRC" ]]; then rsync -a --ignore-existing "$REPO_DATA_SRC/" "$DATA_DIR/"; fi
chmod 700 "$DATA_DIR/ssh"

log "Refreshing terminal helper"
install -m 0644 "$TERMINAL_SRC/package.json" "$TERMINAL_DST/package.json"
install -m 0644 "$TERMINAL_SRC/server.js" "$TERMINAL_DST/server.js"
install -m 0644 "$TERMINAL_SRC/composerize.js" "$TERMINAL_DST/composerize.js"
(cd "$TERMINAL_DST" && npm install --omit=dev --no-audit --no-fund)
install -d -m 0755 "$APP_DST/public/vendor/xterm"
install -m 0644 "$TERMINAL_DST/node_modules/@xterm/xterm/lib/xterm.js" "$APP_DST/public/vendor/xterm/xterm.js"
install -m 0644 "$TERMINAL_DST/node_modules/@xterm/xterm/css/xterm.css" "$APP_DST/public/vendor/xterm/xterm.css"

log "Configuring PHP $PHP_VERSION"
install -m 0644 "$PHP_INI_SRC" "/etc/php/${PHP_VERSION}/fpm/conf.d/99-dockermanger.ini"
install -m 0644 "$PHP_INI_SRC" "/etc/php/${PHP_VERSION}/cli/conf.d/99-dockermanger.ini"
printf '[www]\nclear_env = no\n' > "$PHP_FPM_OVERRIDE"
if getent group docker >/dev/null; then usermod -aG docker www-data; fi
if [[ "$MANAGE_STACK_PERMS" == true ]]; then
  setfacl -Rm u:www-data:rwX "$STACKS_DIR"
  setfacl -Rm d:u:www-data:rwX "$STACKS_DIR"
fi

log "Preserving/creating TLS certificate"
CRT="$DATA_DIR/certs/dockermanger.crt"
KEY="$DATA_DIR/certs/dockermanger.key"
if [[ -e "$CRT" || -e "$KEY" ]]; then
  [[ -f "$CRT" && -f "$KEY" ]] || die "Incomplete TLS pair under $DATA_DIR/certs."
else
  HOST_CN="$(hostname -f 2>/dev/null || hostname)"
  openssl req -x509 -nodes -newkey rsa:2048 -days 825 -keyout "$KEY" -out "$CRT" -subj "/CN=$HOST_CN" >/dev/null 2>&1
  chmod 600 "$KEY"; chmod 644 "$CRT"
fi

cat > "$TMP_DIR/dockermanger.env" <<EOF
TZ=$TIMEZONE
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
STACKS_DIR=$STACKS_DIR
DOCKERMANGER_HTTPS_PORT=$HTTPS_PORT
DOCKERMANGER_ENABLE_CONSOLE=$ENABLE_CONSOLE
DOCKERMANGER_TERMINAL_TYPE=xterm-256color
DOCKERMANGER_CONSOLE_DEFAULT_TARGET=local
DOCKERMANGER_TERMINAL_PORT=3000
DOCKERMANGER_HOST_SHELL_ENABLED=false
DOCKERMANGER_HOST_SSH_HOST=127.0.0.1
DOCKERMANGER_HOST_SSH_PORT=22
DOCKERMANGER_HOST_SSH_USER=root
DOCKERMANGER_HOST_SSH_KEY=
EOF
install -m 0640 "$TMP_DIR/dockermanger.env" "$ENV_DST"

install -d -m 0755 "$PHP_FPM_DROPIN"
cat > "$PHP_FPM_DROPIN/10-dockermanger.conf" <<EOF
[Service]
EnvironmentFile=$ENV_DST
EOF

log "Generating nginx configuration"
cat > "$TMP_DIR/dockermanger.conf" <<EOF
# Generated by DockerManger host_installer.sh.
server {
    listen $HTTP_PORT;
    listen [::]:$HTTP_PORT;
    server_name _;

    location = /health {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $APP_DST/public/health.php;
        fastcgi_param SCRIPT_NAME /health.php;
        fastcgi_pass unix:$PHP_FPM_SOCK;
    }

    location ^~ /.well-known/acme-challenge/ {
        root $ACME_DIR;
        default_type "text/plain";
        try_files \$uri =404;
    }

    location / { return 302 https://\$host:$HTTPS_PORT\$request_uri; }
}

server {
    listen $HTTPS_PORT ssl;
    listen [::]:$HTTPS_PORT ssl;
    server_name _;
    root $APP_DST/public;
    index index.php;

    ssl_certificate $CRT;
    ssl_certificate_key $KEY;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:DockerMangerSSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "same-origin" always;

    location = /health {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root/health.php;
        fastcgi_param SCRIPT_NAME /health.php;
        fastcgi_pass unix:$PHP_FPM_SOCK;
    }

    location = /terminal-ws {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
    }

    location / { try_files \$uri \$uri/ /index.php?\$query_string; }
    location ~ \.php\$ {
        try_files \$uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME \$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_pass unix:$PHP_FPM_SOCK;
    }
    location ~ /\.(?!well-known) { deny all; }
    client_max_body_size 10m;
}
EOF

# Guard against the exact corruption seen during the first test: nginx directives
# must exist in the generated nginx file, never as executable shell lines.
grep -Fxq '    ssl_session_tickets off;' "$TMP_DIR/dockermanger.conf" || die "Generated nginx configuration self-check failed."
install -m 0644 "$TMP_DIR/dockermanger.conf" "$NGINX_DST"
if [[ -L /etc/nginx/sites-enabled/default ]] && { [[ "$HTTP_PORT" == 80 ]] || [[ "$HTTPS_PORT" == 443 ]]; }; then rm -f /etc/nginx/sites-enabled/default; fi
ln -sfn "$NGINX_DST" /etc/nginx/sites-enabled/dockermanger.conf

cat > "$TMP_DIR/dockermanger-terminal.service" <<EOF
[Unit]
Description=DockerManger browser terminal service
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$ENV_DST
WorkingDirectory=$TERMINAL_DST
ExecStart=/usr/bin/node $TERMINAL_DST/server.js
Restart=on-failure
RestartSec=2
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF
install -m 0644 "$TMP_DIR/dockermanger-terminal.service" "$SYSTEMD_DST"

log "Validating generated configuration before service restart"
php-fpm${PHP_VERSION} -t
nginx -t

systemctl daemon-reload
systemctl enable "$PHP_FPM_SERVICE" nginx >/dev/null
systemctl restart "$PHP_FPM_SERVICE" nginx
if [[ "$ENABLE_CONSOLE" == true ]]; then
  systemctl enable --now dockermanger-terminal.service
else
  systemctl disable --now dockermanger-terminal.service 2>/dev/null || true
fi

log "Running final checks"
FAIL=0
if [[ "$INSTALL_DOCKER" == true || -x "$(command -v docker 2>/dev/null || true)" ]]; then
  docker version >/dev/null 2>&1 || { warn "Docker Engine check failed."; FAIL=1; }
  docker compose version >/dev/null 2>&1 || { warn "Docker Compose v2 check failed."; FAIL=1; }
fi
systemctl is-active --quiet "$PHP_FPM_SERVICE" || { warn "$PHP_FPM_SERVICE inactive."; FAIL=1; }
systemctl is-active --quiet nginx || { warn "nginx inactive."; FAIL=1; }
curl -fsS "http://127.0.0.1:$HTTP_PORT/health" >/dev/null || { warn "HTTP health check failed."; FAIL=1; }
curl -kfsS "https://127.0.0.1:$HTTPS_PORT/health" >/dev/null || { warn "HTTPS health check failed."; FAIL=1; }

HOST_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"; HOST_IP="${HOST_IP:-HOST-IP}"
cat <<EOF

============================================================
DockerManger native host install/repair complete
============================================================
Web UI      : https://$HOST_IP:$HTTPS_PORT
App copy    : $APP_DST
Runtime data: $DATA_DIR       (preserved on every rerun)
Stacks      : $STACKS_DIR     (preserved on every rerun)
Settings    : $INSTALLER_CONF (reused automatically)
PHP-FPM     : $PHP_FPM_SERVICE

Re-run ./host_installer.sh after a git pull to update/repair the native install.
To intentionally change a saved option, either edit $INSTALLER_CONF or run, e.g.:
  HTTPS_PORT=8443 ./host_installer.sh
EOF
(( FAIL == 0 )) || exit 2
