<?php
declare(strict_types=1);
$escape = static fn(mixed $v): string => htmlspecialchars((string)$v, ENT_QUOTES|ENT_SUBSTITUTE, 'UTF-8');
$stateLabel = static fn(string $s): string => ucfirst($s);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/css/app.css"><title><?= isset($selected)?$escape($selected['name']).' · ':'' ?>DockerManger</title></head>
<body><div class="app-shell"><header class="topbar"><a class="brand" href="/"><span class="logo">DM</span><span><strong>DockerManger</strong><small>Compose &amp; container management</small></span></a><div class="top-actions"><a class="button button-secondary" href="/">← Dashboard</a></div></header><div class="layout">
<aside class="sidebar"><div class="sidebar-head"><div><span class="eyebrow">Compose</span><h2>Stacks</h2></div><a class="button button-small" href="/#new-stack">+ Compose</a></div><label class="search-box"><span class="sr-only">Search stacks</span><input id="stack-search" type="search" placeholder="Search stacks..."></label><nav class="stack-list">
<?php foreach($stacks as $stack): ?><a class="stack-item stack-link <?= isset($selected)&&$stack['name']===$selected['name']?'selected':'' ?>" data-stack-name="<?= $escape(strtolower($stack['name'])) ?>" href="/?stack=<?= urlencode($stack['name']) ?>"><div class="stack-title"><span class="status <?= $escape($stack['state']) ?>"></span><strong><?= $escape($stack['name']) ?></strong></div><span class="stack-state"><?= $escape($stateLabel($stack['state'])) ?></span><small><?= (int)$stack['running'] ?> running / <?= (int)$stack['stopped'] ?> stopped</small></a><?php endforeach; ?>
</nav></aside>
<main class="content"><?php if(isset($pageError)): ?><section class="notice notice-error"><strong><?= $escape($pageError) ?></strong></section><?php else: ?>
<section class="page-heading stack-heading"><div><span class="eyebrow">Compose Stack</span><h1><span class="status <?= $escape($selected['state']) ?>"></span><?= $escape($selected['name']) ?></h1><p><?= $escape($selected['composeFile']) ?> · <?= $escape($selected['state']) ?> · <?= (int)$selected['containerCount'] ?> containers</p></div><a class="button button-secondary" href="/">Dashboard</a></section>
<section class="stack-actions" data-stack="<?= $escape($selected['name']) ?>" data-csrf="<?= $escape(csrf_token()) ?>"><button class="button stack-action" data-action="stack-start">Start</button><button class="button button-secondary stack-action" data-action="stack-stop">Stop</button><button class="button button-secondary stack-action" data-action="stack-restart">Restart</button><button class="button stack-action" data-action="stack-update">Update</button><button class="button button-danger stack-action" data-action="stack-down">Down</button></section><div id="action-result" class="operation-output" hidden></div>
<?php if(empty($selected['valid'])): ?><div class="notice notice-error"><strong>Compose validation failed.</strong><span><?= $escape($selected['validationError']) ?></span></div><?php endif; ?>
<div class="stack-grid"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">Containers</span><h2>Stack Containers</h2></div><span class="count-badge"><?= count($selected['containers']) ?></span></div><?php if(!$selected['containers']): ?><div class="empty"><strong>No containers created yet</strong><span>Use Start to create and launch this stack.</span></div><?php else: ?><div class="container-cards"><?php foreach($selected['containers'] as $c): ?><article class="container-card"><div><span class="container-state <?= $escape($c['state']) ?>"><span class="status-dot"></span><?= $escape($c['status']) ?></span><h3><?= $escape($c['name']) ?></h3><p><?= $escape($c['image']) ?></p><small><?= $escape($c['ports']?:'No published ports') ?></small></div><div class="container-card-actions"><a class="button button-secondary button-small" href="/console.php?container=<?= urlencode($c['name']) ?>">Console</a><button class="button button-secondary button-small log-container" data-container="<?= $escape($c['name']) ?>">Logs</button></div></article><?php endforeach; ?></div><?php endif; ?></section>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Compose</span><h2><?= $escape($selected['file']) ?></h2></div><span class="validity <?= $selected['valid']?'good':'bad' ?>"><?= $selected['valid']?'Valid':'Invalid' ?></span></div><form id="compose-editor" data-stack="<?= $escape($selected['name']) ?>" data-csrf="<?= $escape(csrf_token()) ?>"><textarea class="compose-editor" name="compose" spellcheck="false"><?= $escape($composeText) ?></textarea><div class="editor-actions"><button class="button" type="submit">Validate &amp; Save</button><span class="muted-cell">Changes are validated before replacing the current file.</span></div></form></section></div>
<section class="panel"><div class="panel-heading"><div><span class="eyebrow">Logs</span><h2>Stack Logs</h2></div><button id="refresh-logs" class="button button-secondary button-small" data-stack="<?= $escape($selected['name']) ?>">Refresh Logs</button></div><pre id="stack-logs" class="log-viewer"><?= $escape($stackLogs['output']??'') ?></pre></section>
<?php endif; ?></main></div></div><script src="/js/app.js"></script></body></html>
